[package]
name = "fiat-shamir"
version.workspace = true
edition.workspace = true

[dependencies]
p3-field.workspace = true
serde.workspace = true
p3-symmetric.workspace = true
rayon.workspace = true
p3-koala-bear.workspace = true
p3-poseidon2.workspace = true
